name: Advanced Usage

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    env:
      FILELIST:  lorem_1.md lorem_2.md README.md 
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Lorem ipsum" > lorem_1.md  # create two example files
          echo "dolor sit amet" > lorem_2.md
          mkdir output  # create output dir
          # this will also include README.md
          # echo "::set-env name=FILELIST::$(printf '"%s" ' *.md)"
      - uses: docker://pandoc/latex:2.9
        with:
          args: --output=output/result.pdf ${{ env.FILELIST }}
      - uses: actions/upload-artifact@master
        with:
          name: output
          path: output
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: output/result.pdf
          retention-days: 5
